apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: elk
  name: elasticsearch-pv
  labels:
    name: elasticsearch
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # 한 개의 노드에서만 읽고 쓸 수 있음
  claimRef: # 연결할 PVC를 지정
    namespace: elk
    name: elasticsearch-persistent-storage-elasticsearch-node-0
  persistentVolumeReclaimPolicy: Delete # PVC를 삭제하면 볼륨도 자동으로 삭제 -> 데이터를 보존하려면 Retain 정책을 사용할 것
  hostPath:
    path: /data/es
    type: DirectoryOrCreate # 디렉터리가 존재하면 매핑, 없으면 새로 생성 후 매핑
