# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
# Create Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: elasticsearch-config
  labels:
    name: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    network.host: 0.0.0.0
---
# Create StatefulSet and Pod
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elastic/elasticsearch:7.11.1
          # resources:
          #   limits:
          #     cpu: 1000m
          #     memory: 200Mi
          #   requests:
          #     cpu: 100m
          #     memory: 200Mi
          env:
            - name: CLUSTER_NAME
              value: es-0
            - name: NODE_NAME
              value: node-0
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
              subPath: elasticsearch.yml
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_cluster/health
          #     port: http
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: elasticsearch-config
---
# Create Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-svc
  namespace: elk
spec:
  ports:
    - name: elasticsearch-rest
      nodePort: 30920
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: elasticsearch-nodecom
      nodePort: 30930
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch
  type: NodePort
