# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
# Create Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: elasticsearch-config
  labels:
    name: elasticsearch
    #role: data
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    # node.name: ${NODE_NAME}
    network.host: ["_local_", "_site_"]
---
# Create StatefulSet and Pod
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
          # resources:
          #   limits:
          #     cpu: 1000m
          #     memory: 200Mi
          #   requests:
          #     cpu: 100m
          #     memory: 200Mi
          env:
            - name: CLUSTER_NAME
              value: es-0
            # - name: NODE_NAME
            #   value: node-0
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
              subPath: elasticsearch.yml
            - name: tz-seoul
              mountPath: /etc/localtime
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_cluster/health
          #     port: http
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: elasticsearch-config
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
---
# Create Service
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-svc
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
    - name: rest
      port: 9200
    - name: transport
      port: 9300
  selector:
    app: elasticsearch
---
# Create Service
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-nodeport
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - nodePort: 30920
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: elasticsearch
