# Create Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: logstash-config
  labels:
    task: logging
    app: logstash
data:
  logstash.yml: |-
    http.host: "127.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |-
    input
    {
      tcp
      {
        port => 5000
      }
    }
    filter
    {
      json
      {
        source => "message"
        remove_field => ["@version", "beat", "count","fields","input_type","offset","source","host","tags","port","message"]
      }
    }
    output
    {
      elasticsearch
      {
        hosts => ["${ELASTICSEARCH_HOSTS}"]
        manage_template => false
        index => "my_index"
        document_type => "doc"
      }
    }
---
# Create Deployment
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: elk
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:7.10.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: logstash-tcp
              containerPort: 5000
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-svc:9200"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
---
# Create Service
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash-svc
  labels:
    app: logstash
spec:
  ports:
    - name: logstash-tcp
      port: 5000
  selector:
    app: logstash
